### ISSUE TITLE
vagrant up

### ISSUE THREAD

**Issue by dpJoker** [gigigoapps/ubuntu1404-mongodb26#7]
$ vagrant up
Bringing machine 'ubuntumongo' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
- The following settings shouldn't exist: box_version
- The box 'puppetlabs/ubuntu-14.04-64-puppet' could not be found.

**Comment by pserrano** [comment]
Hi @dpJoker Do you execute "vagrant init puppetlabs/ubuntu-14.04-64-puppet"?

**Comment by pserrano** [comment]
@dpJoker Which version of vagrant have you installed?

**Comment by dpJoker** [comment]
Hi @pserrano 
version 1.4.3

$ vagrant init puppetlabs/ubuntu-14.04-64-puppet
`Vagrantfile` already exists in this directory. Remove it before
running `vagrant init`.                                         

Vagrantfile already there because I made git clone from your repo.

**Comment by pserrano** [comment]
@dpJoker ok, you have a old vagrant version. 

You will need:

Git 1.7+
Vagrant v1.6.5 + (http://vagrantup.com)
Virtualbox v4.3.16 + (https://www.virtualbox.org/)

**Comment by dpJoker** [comment]
thanks, please close this issue.
